######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 16 04:02:41 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += webkit opengl

# Input
HEADERS += browser.h
SOURCES += main.cpp browser.cpp
